export type FeaturesUrls = {
  rewards_customer_enrollment: { href: string }
  change_password: { href: string }
  enabled_features: { href: string }
  certificate_status: { href: string }
  rosetta_localization: { href: string }
  revoke_token: { href: string }
  userinfo: { href: string }
  events_page: { href: string }
  loginWebapp: { href: string }
  dropman: { href: string }
  events: { href: string }
  register_rewards: { href: string }
  login_webapp: { href: string }
  postcode: { href: string }
  app_flows: { href: string }
  rewards_signup_widget: { href: string }
  revoke_all: { href: string }
  customer: { href: string }
  account: { href: string }
  bills_summary: { href: string }
  features_map: { href: string }
  healthcheck: { href: string }
  savings_account: { href: string }
  rewards_enrollment: { href: string }
  purchases: { href: string }
  blackmirror: { href: string }
  ghostflame: { href: string }
  revelio: { href: string }
  canuto: { href: string }
  shore: { href: string }
  user_change_password: { href: string }
  rosetta_localizations_by_locale: { href: string }
}
