name: Checks

on: [push]

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm i
    - name: Check code format and stylle
      run: npm run lint
    - name: Check typescript types
      run: npm run types:check
    - name: Run tests
      run: npm run test
